# Change these first
owner: privatereese # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Webseite
    url: https://www.edvgarbe.de
  - name: Nextcloud
    url: https://cloud.edvgarbe.de
  - name: Mail
    url: https://mail.edvgarbe.de
  - name: Bitwarden
    url: https://bitwarden.edvgarbe.de
  - name: Suche
    url: https://suche.edvgarbe.de
  - name: Matrix
    url: https://matrix.edvgarbe.de
  - name: Latex
    url: https://latex.edvgarbe.de
  - name: HedgeDoc
    url: https://md.edvgarbe.de
  - name: Mastodon
    url: https://mastodon.edvgarbe.de
  - name: Wallabag
    url: https://wallabag.edvgarbe.de
  - name: IRC
    url: https://irc.edvgarbe.de


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: https://privatereese.github.io/uuptime/
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime EDVGarbe
  introTitle: "**Upptime** EDVGarbe zeigt die aktuelle und vergangene Verfügbarkeit der Dienste von EDVGarbe an"
  introMessage: Diese Liste erhebt keinen Anspruch auf Vollständigkeit. Falls Dienste fehlen bitte gerne jederzeit unter [info@edvgarbe.de](mailto:info@edvgarbe.de) melden.
  navbar:
    - title: Status
      href: /
    - title: Fehler melden
      href: https://github.com/$OWNER/$REPO/issues

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
